### ISSUE TITLE
Python codegen does not default generic vector fields

### ISSUE THREAD

**Issue by naegelejd** [microsoft/yardl#100]
There is another issue. 
``` yaml
MyRec<T>: !record
  fields:
    a: T*
```

Does not default the field, whereas this does: 
``` yaml
MyRec: !record
  fields:
    a: int*
```

(An existing issue, not a regression)

_Originally posted by @johnstairs in https://github.com/microsoft/yardl/issues/96#issuecomment-1802003649_
