### ISSUE TITLE
Python `get_dtype` does not work for vectors, arrays, and maps

### ISSUE THREAD

**Issue by naegelejd** [microsoft/yardl#110]
Using the [current](https://github.com/microsoft/yardl/tree/e01fb0f4b3c571b515978bb31bd2452c076560ba) test model, yardl throws a `RuntimeError: Cannot find dtype` for **each** of the following true assertions:

```python
import test_model as tm

assert tm.get_dtype(tm.AliasedGenericVector[int]) == np.object_

assert tm.get_dtype(tm.AliasedGenericFixedVector[int]) == np.int32

assert tm.get_dtype(tm.AliasedGenericDynamicArray[int]) == np.object_

assert tm.get_dtype(tm.AliasedGenericFixedArray[int]) == np.int32

assert tm.get_dtype(tm.basic_types.AliasedMap[str, int]) == np.object_
```

**Comment by naegelejd** [comment]
Here is a related example for non-generic arrays. Given the following model:
```yaml
IntFixedArray: int[2, 3]

RecordWithFixedArrays: !record
  fields:
    ints: int[2, 3]

RecordWithNamedFixedArrays: !record
  fields:
    ints: IntFixedArray
```

`get_dtype` returns the same dtype for both records:
```python
{'names': ['ints'], 'formats': [('<i4', (2, 3))], 'offsets': [0], 'itemsize': 24, 'aligned': True}
```

However, if I define a non-fixed array type **before** the fixed array type, like so
```yaml
IntArray: int[]
IntFixedArray: int[2, 3]

...
```

then `get_dtype` returns a new, incorrect `dtype` for `RecordWithNamedFixedArrays`:
```python
{'names': ['ints'], 'formats': [('O', (2, 3))], 'offsets': [0], 'itemsize': 48, 'aligned': True}
```

This extends to vectors as well.
