### ISSUE TITLE
Python union classes generated with duplicate type parameters

### ISSUE THREAD

**Issue by naegelejd** [microsoft/yardl#111]
Using the following model:

```yaml
GenericUnion<T>: !union
  t: T
  tv: T*
  tvf: T[]
```
yardl v0.4.0 generates invalid Python:
```python
class GenericUnion(typing.Generic[T, T_NP, T, T_NP, T, T_NP]):
```
Error message on import:
```python
TypeError: Parameters to Generic[...] must all be unique
```
