### ISSUE TITLE
Python syntax/type errors when default union type is list or dict

### ISSUE THREAD

**Issue by naegelejd** [microsoft/yardl#112]
Given the following model:
```yaml
GenericUnionsRecord<T, U>: !record
  fields:
    a: !union
      tv: T*
      t: T
    b: !union
      tm: T->U
      t: T
```
yardl v0.4.0 generates invalid constructor code for both inner unions:
```python
class GenericUnionsRecord(typing.Generic[T, T_NP, U]):
    ...

    def __init__(self, *, ...):
        self.a = a if a is not None else TvOrT.Tv([]())
        self.b = b if b is not None else TmOrT.Tm({}())
```

Warnings on import (these are TypeErrors at runtime):
```python
/workspaces/yardl/joe/issue-#112/python/odd/types.py:58: SyntaxWarning: 'list' object is not callable; perhaps you missed a comma?
  self.a = a if a is not None else TvOrT.Tv([]())
/workspaces/yardl/joe/issue-#112/python/odd/types.py:59: SyntaxWarning: 'dict' object is not callable; perhaps you missed a comma?
  self.b = b if b is not None else TmOrT.Tm({}())
```

This issue occurs when the *first* type in the union resolves to a Python `list` or `dict`.
