### ISSUE TITLE
Unable to create switch expression of type string

### ISSUE THREAD

**Issue by naegelejd** [microsoft/yardl#113]
Using yardl v0.4.0, I expect to be able to use a computed field switch expression to produce a string value:

```yaml
RecordWithComputedFields: !record
  fields:
    myField: [null, string, float]
  computedFields:
    myResult:
      !switch myField:
        null: "null"
        string: "string"
        float: "float"
```
But yardl complains with:
```
❌ /workspaces/yardl/joe/switch-case-string/model/model.yml:6:14: there is no variable in scope with the name 'null' nor does the record 'RecordWithComputedFields' does not have a field or computed field named 'null'
❌ /workspaces/yardl/joe/switch-case-string/model/model.yml:7:18: there is no variable in scope with the name 'string' nor does the record 'RecordWithComputedFields' does not have a field or computed field named 'string'
❌ /workspaces/yardl/joe/switch-case-string/model/model.yml:8:17: there is no variable in scope with the name 'float' nor does the record 'RecordWithComputedFields' does not have a field or computed field named 'float'
```
