### ISSUE TITLE
Panic when generating Python/MATLAB for Enum with no default value

### ISSUE THREAD

**Issue by naegelejd** [microsoft/yardl#168]
In Yardl, one can define an Enum type that does *not* have a default value (because there is no "zero" value).

Currently, the Python and MATLAB codegen panic when generating constructors for (nested) records that contain such an Enum.

Given the following model for example:
```yaml
ImageType: !enum
  values:
    magnitude: 1
    phase: 2
    real: 3
    imag: 4
    complex: 5

ImageHeader: !record
  fields:
    imageType: ImageType

Image: !record
  fields:
    head: ImageHeader
```
in which `ImageType` does *not* have a "zero" value, Yardl panics:
```
panic: No typeDefault for record field ImageHeader.imageType

goroutine 1 [running]:
github.com/microsoft/yardl/tooling/internal/python/types.typeDefinitionDefault({0x8804e0?, 0xc000373180?}, {0xc0001ed8c8, 0x3}, 0x8?)
        /home/runner/work/yardl/yardl/tooling/internal/python/types/types.go:969 +0xcbd
github.com/microsoft/yardl/tooling/internal/python/types.typeDefault({0x8804b8?, 0xc000381e00?}, {0xc0001ed8c8?, 0x4?}, {0x0?, 0x1?}, 0x1?)
        /home/runner/work/yardl/yardl/tooling/internal/python/types/types.go:831 +0x65
github.com/microsoft/yardl/tooling/internal/python/types.writeRecord.func1.1()
        /home/runner/work/yardl/yardl/tooling/internal/python/types/types.go:210 +0x225
...
```

It looks like an easy fix. Incoming.
