### ISSUE TITLE
Invalid defaulting of union in record

### ISSUE THREAD

**Issue by johnstairs** [microsoft/yardl#179]
```yaml
A: !record
  fields:
    value: int

B: int

Container: !record
  fields:
    aOrB: [A, B]
```

Generates:
```python
class Container:
    a_or_b: AOrB

    def __init__(self, *,
        a_or_b: typing.Optional[AOrB] = None,
    ):
        self.a_or_b = a_or_b if a_or_b is not None else AOrB.A(A()())
```

`A()()` in the last line is invalid.
