### ISSUE TITLE
return type of generated functions in C++

### ISSUE THREAD

**Issue by KrisThielemans** [microsoft/yardl#197]
How dies yardl decide the return type of computed fields?

I have the following
```
ScannerInformation: !record
  fields:
    eventEnergyBinEdges: !array
      items: float
      dimensions: 1

  computedFields:
    numberOfEventEnergyBins: size(eventEnergyBinEdges)-1
```
This results in generated code
```
  yardl::Size NumberOfEventEnergyBins() const {
    return event_energy_bin_edges.size() - 1ULL;
  }
```
(This is maybe the wrong convention to use, but that's not the point of this issue.)

It turns out that in our application, the size of the array can be 0. (There is then another flag to indicate this). This results in a return value of 18446744073709551615. It's not a major problem for us, but it seems that some choice was made that could be inappropriate.
