### ISSUE TITLE
multi-dim arrays

### ISSUE THREAD

**Issue by KrisThielemans** [microsoft/yardl#20]
https://github.com/microsoft/yardl/blob/main/docs/docs.md#computed-fields states
```
MyRec: !record
  fields:
    arrayField: !array
        items: int
        dimensions: [x, y]
  computedFields:
    accessArrayElementByName: arrayField[y:1, x:0]
```
this swaps the order between `dimensions` and access. Is this intentional? It'd be very confusing!

Also, somewhere in the doc we'll need a description of mappings between yardl types and C++ and other target languages. In particular, I believe you generate your own multi-dim array type as there still doesn't seem to be an `std`  container sadly.

It could be useful to support a few existing multi-dim arrays to avoid copies in client-code (Boost.MultiArray and https://amypad.github.io/CuVec/ come to mind), but I can see that becoming very difficult. (If a mapping to a flat array is exposed somewhere, it'd need to be stated if row-major or column-major order is used).
