### ISSUE TITLE
where to generate C++ files

### ISSUE THREAD

**Issue by KrisThielemans** [microsoft/yardl#220]
At present, [our package.yml](https://github.com/ETSInitiative/PETSIRD/blob/df88a052f706cdbc69dfdad5ea08e6bc42ca081d/model/_package.yml#L1-L10) has
```
namespace: PETSIRD
cpp:
  sourcesOutputDir: ../cpp/generated
python:
  outputDir: ../python
```
This results in files `../cpp/generated/types.h` etc, and `../python/petsird/types.py` etc. The C++ choice is different from Python/MATLAB, and creates trouble for `target_include_directories`, see #104.

I think the following file structure would make more sense

- ../cpp/generated # or whatever was specified in the package.yml
  -  CMakeLists.txt
      petsird # or whatever the namespace is
     -  types.h
     - ...

Aside from this, I see no good reason for yardl to change the casing of the specified namespace. Shouldn't this be up to the user?
