### ISSUE TITLE
Size is a valid enum type for code generation but fails compilation

### ISSUE THREAD

**Issue by v-kylegre** [microsoft/yardl#26]
When you define an enum with a size base, you succeed in code generation, but the code fails to compile

```
MyEnum: !enum
  base: size 
  values:
    a: 1 
    b: 2
    c: 3
```
