### ISSUE TITLE
Support maps

### ISSUE THREAD

**Issue by johnstairs** [microsoft/yardl#47]
We should support maps/dictionaries as a first-class datatype. Syntax could be something like:
```yaml
x: !map
  keys: string
  values: int
```

Keys can only be primitive scalar types. 

Shorthand syntax could look like:

```yaml
string->int
```

We should also make sure maps can be used in computed fields.
