### ISSUE TITLE
Support flags enums

### ISSUE THREAD

**Issue by johnstairs** [microsoft/yardl#49]
We should have a special kind of enum for flags that are meant to be bitwise ORed together:

```yaml
!flags
  values:
    - none
    - red
    - green
    - blue
```

The first value will always be 0.

As with enums, you can specify the base type and integer values:

```yaml
!flags
  values:
    none: 0
    red: 1
    green: 2
    blue: 4
```
